"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['main.py']  # Main application file
DATA_FILES = ["favIcon.png"]  # List of data files to include
OPTIONS = {
    "argv_emulation": False,
    "packages": ["rumps", "pynput"],  # Include necessary packages
    "plist": {
        "CFBundleIconFile": "favIcon.png",  # Specify the app icon
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
